
GET http://localhost:5000/

###
GET http://localhost:5000/api/v1

###
POST http://localhost:5000/api/v1
Content-Type: application/json

{
    "text":"salary",
    "amount":10000
}
###
DELETE http://localhost:5000/api/v1/5feed3417650310fdd8c84ec
